// Reading lessons are generated by AI on-demand via /api/reading
// No hardcoded lessons — all content is real AI-generated content

export type ReadingLesson = {
  id: string;
  title: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  topic: string;
  emoji: string;
  language: string;
  locked: boolean;
  passage: string;
  translation: string;
  vocabulary: { word: string; translation: string; example: string }[];
  questions: { question: string; answer: string; type?: string }[];
};

// Topic suggestions per level — used to seed AI generation
export const TOPIC_SUGGESTIONS: Record<string, { topic: string; emoji: string }[]> = {
  A1: [
    { topic: "My Daily Routine", emoji: "🌅" },
    { topic: "My Family", emoji: "👨‍👩‍👧‍👦" },
    { topic: "My Favorite Food", emoji: "🍜" },
    { topic: "My School", emoji: "🏫" },
    { topic: "My Hobbies", emoji: "🎮" },
    { topic: "Animals", emoji: "🐾" },
    { topic: "Colors and Numbers", emoji: "🎨" },
    { topic: "The Weather", emoji: "☀️" },
  ],
  A2: [
    { topic: "A Trip to the Beach", emoji: "🏖️" },
    { topic: "Technology in Our Lives", emoji: "📱" },
    { topic: "My Favorite Season", emoji: "🍂" },
    { topic: "Shopping", emoji: "🛍️" },
    { topic: "Sports and Exercise", emoji: "⚽" },
    { topic: "Music and Entertainment", emoji: "🎵" },
    { topic: "Cooking at Home", emoji: "👨‍🍳" },
    { topic: "Public Transport", emoji: "🚌" },
  ],
  B1: [
    { topic: "Climate Change", emoji: "🌍" },
    { topic: "The History of Coffee", emoji: "☕" },
    { topic: "Social Media", emoji: "📲" },
    { topic: "Healthy Lifestyle", emoji: "🥗" },
    { topic: "Travel and Tourism", emoji: "✈️" },
    { topic: "Education Systems", emoji: "📚" },
    { topic: "Traditional Festivals", emoji: "🎉" },
    { topic: "Urban vs Rural Life", emoji: "🏙️" },
  ],
  B2: [
    { topic: "Artificial Intelligence", emoji: "🤖" },
    { topic: "Mental Health Awareness", emoji: "🧠" },
    { topic: "Globalization", emoji: "🌐" },
    { topic: "Renewable Energy", emoji: "⚡" },
    { topic: "The Gig Economy", emoji: "💼" },
    { topic: "Space Exploration", emoji: "🚀" },
    { topic: "Biodiversity Loss", emoji: "🦋" },
    { topic: "Digital Privacy", emoji: "🔒" },
  ],
  C1: [
    { topic: "Philosophy of Mind", emoji: "💭" },
    { topic: "Economic Inequality", emoji: "📊" },
    { topic: "Geopolitics", emoji: "🗺️" },
    { topic: "Neuroscience and Behavior", emoji: "🧬" },
    { topic: "Ethics in Technology", emoji: "⚖️" },
    { topic: "Post-Colonial Literature", emoji: "📖" },
    { topic: "Quantum Computing", emoji: "💻" },
    { topic: "Behavioral Economics", emoji: "💰" },
  ],
  C2: [
    { topic: "Epistemology and Knowledge", emoji: "🔭" },
    { topic: "Critical Theory", emoji: "📜" },
    { topic: "Advanced Linguistics", emoji: "🗣️" },
    { topic: "Transhumanism", emoji: "🦾" },
    { topic: "Climate Justice", emoji: "⚖️" },
    { topic: "Consciousness and Identity", emoji: "🌀" },
  ],
};
